package main

import (
	_ "./docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/gin-gonic/gin"
	"github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
	"higo/h_gin/controller"
	"higo/h_gin/controller/rbac"
	"higo/h_gin/middleware/jwt"
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host 127.0.0.1:8080
// @BasePath /v1
func main() {
	r := gin.Default()
	gin.SetMode("debug")

	//Api文档
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	//WebSocket
	r.GET("/v1/web/socket", controller.WebSocket)

	//测试专用
	r.GET("/v1/test/info", controller.GetTest)
	r.POST("/v1/test/add", controller.PostTest)

	//登录授权
	r.POST("/v1/login/auth", controller.LoginAuth)
	r.POST("/v1/login/check", controller.LoginCheck)

	//权限控制
	apiAdminV1 := r.Group("/v1/admin")
	apiAdminV1.GET("/check/access", rbac.CheckAccess)
	apiAdminV1.GET("/role", rbac.GetRole)
	apiAdminV1.POST("/role", rbac.PostRole)
	apiAdminV1.GET("/permission", rbac.GetPermission)
	apiAdminV1.POST("/permission", rbac.PostPermission)

	apiUserV1 := r.Group("/v1")
	apiUserV1.Use(jwt.JWT())
	{
		//测试路由
		apiUserV1.GET("/user", controller.GetUser)
		apiUserV1.POST("/user", controller.PostUser)
		apiUserV1.PUT("/user", controller.PutUser)
		apiUserV1.DELETE("/user", controller.DeleteUser)
	}

	r.Run(":8080") // listen and serve on 0.0.0.0:8080
}
