package main

import (
	_ "./docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/gin-gonic/gin"
	"github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"
	"higo/h_gin/controller"
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host 127.0.0.1:8080
// @BasePath /v1
func main() {
	r := gin.Default()
	gin.SetMode("debug")

	//Api文档
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	//测试路由
	r.GET("/v1/user", controller.GetUser)
	r.POST("/v1/user", controller.PostUser)
	r.PUT("/v1/user", controller.PutUser)
	r.DELETE("/v1/user", controller.DeleteUser)

	r.Run(":8080") // listen and serve on 0.0.0.0:8080
}
